from agents.state import AuditState
from models.hf_client import HFClient

_client = HFClient()

_SYSTEM = """You are a senior workers' compensation premium auditor drafting a formal audit worksheet.

Write a professional, business-ready audit worksheet in clean Markdown. Follow this exact structure — do not add or remove sections:

# Workers' Compensation Premium Audit Worksheet
**DRAFT — Requires Auditor Review Before Submission**

---

## 1. Policyholder Information
| Field | Details |
|---|---|
| Company | [company name from document] |
| Audit Period | [period from document] |
| Policy Number | [policy number from document] |
| Report Prepared | [today's date] |
| Total Audited Payroll | [sum all employee wages] |

---

## 2. Employee Classification Summary
| Employee | Job Title | NCCI Code | Classification | Payroll | Confidence |
|---|---|---|---|---|---|
[one row per employee — use the classification data provided]

---

## 3. Classification Notes
[One bullet per employee. State why the NCCI code was selected. Mark ⚠ LOW confidence codes as requiring manual verification.]

---

## 4. Subcontractor & COI Review
[If subcontractors are mentioned in the document, list them in a table with COI status. Mark any missing COI with ⚠ and note the reclassification risk. If no subcontractors, write "No subcontractors identified."]

---

## 5. Auditor Action Items
[Numbered list of specific actions the auditor must complete before finalizing the premium. Order by urgency. Keep each item to one sentence.]

---
*Draft generated by AuditPilot AI · Auditor of record must review and approve before submission.*

Rules:
- Use plain business language — no jargon beyond standard WC audit terms
- Use ⚠ for warnings and ✓ for verified items
- Do not invent data — only use what is provided
- Keep the entire report concise and scannable"""


def report_node(state: AuditState) -> AuditState:
    if state.get("error"):
        return state

    audit_report = _client.generate(prompt=_build_prompt(state), system=_SYSTEM)
    return {**state, "audit_report": audit_report, "current_step": "report"}


def _build_prompt(state: AuditState) -> str:
    records     = state.get("employee_records", [])
    suggestions = state.get("ncci_suggestions", [])
    flags       = state.get("completeness_flags", {})
    raw_snippet = (state.get("raw_text") or "")[:2000]

    return (
        "Draft the audit worksheet using the data below.\n\n"

        "=== DOCUMENT TEXT (first 2000 chars — extract company, period, policy) ===\n"
        f"{raw_snippet}\n\n"

        "=== EMPLOYEE CLASSIFICATIONS ===\n"
        f"{_format_combined(records, suggestions)}\n\n"

        "=== COMPLETENESS FLAGS ===\n"
        f"Has payroll data   : {flags.get('has_payroll_data', False)}\n"
        f"Has employee names : {flags.get('has_employee_names', False)}\n"
        f"Has dates          : {flags.get('has_dates', False)}\n"
        f"Missing fields     : {', '.join(flags.get('missing_fields', [])) or 'None'}\n\n"

        "Now write the complete audit worksheet following the Markdown template exactly."
    )


def _format_combined(records: list[dict], suggestions: list[dict]) -> str:
    if not records:
        return "No employee records extracted."

    by_id = {s["employee_id"]: s for s in suggestions}
    lines = []
    for r in records:
        name = r.get("name", "")
        s    = by_id.get(r.get("employee_id"), {})
        job  = ", ".join(r.get("job_description") or []) or "Not specified"
        lines.append(
            f"  Employee       : {name}\n"
            f"  Job Title      : {job}\n"
            f"  Wages          : {r.get('wages') or 'Not specified'}\n"
            f"  NCCI Code      : {s.get('ncci_code') or 'Not identified'}\n"
            f"  Classification : {s.get('classification') or 'Not identified'}\n"
            f"  Confidence     : {s.get('confidence', 'LOW')}\n"
            f"  Rationale      : {s.get('rationale', '')}"
        )
    return "\n\n".join(lines)
